(function(){const SEARCH_INPUT_ID='pt1:r1:0:pt1:it22::content';const PANELBOX_ID='pt1:r1:0:pt1:pb3';const batchTracker=new Map();function isScannerSafeEnter(e){const now=Date.now();if(!e.isTrusted)return!1;if(!window._lastSafeEnterTime)window._lastSafeEnterTime=0;if(now-window._lastSafeEnterTime<50)return!1;window._lastSafeEnterTime=now;return e.key==='Enter'};function sendToGeidea(amount){fetch('http://localhost:5000/charge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount})})}
if(!window._processedSelectKeys)window._processedSelectKeys=new Set();function init(){const container=document.getElementById(PANELBOX_ID);if(container){container.querySelectorAll('select').forEach(sel=>{const key=computeKey(sel);if(key)window._processedSelectKeys.add(key);})}
const observer=new MutationObserver(mutationsList=>{for(const m of mutationsList){for(const node of m.addedNodes){if(node.nodeType!==1)continue;if(node.tagName==='TR'){const sel=node.querySelector('select');const qtyTd=node.querySelector('td:nth-child(4) td');if(sel&&sel.options.length>1&&qtyTd){batchTracker.set(sel,qtyTd);handleSelect(sel)}}else{node.querySelectorAll?.('select').forEach(sel=>{const tr=sel.closest('tr');const qtyTd=tr?.querySelector('td:nth-child(4) td');if(qtyTd){batchTracker.set(sel,qtyTd);handleSelect(sel)}})}}
for(const node of m.removedNodes){if(node.nodeType!==1)continue;if(node.tagName==='TR'){const sel=node.querySelector('select');if(sel)batchTracker.delete(sel);}else{node.querySelectorAll?.('select').forEach(sel=>{batchTracker.delete(sel)})}}}
batchTracker.forEach((qtyTd,sel)=>{applyBatchColorLogic(sel)})});observer.observe(container,{childList:!0,subtree:!0});document.addEventListener('keydown',onUserKeydown,!0);container.querySelectorAll('tr').forEach(tr=>{const sel=tr.querySelector('select');const qtyTd=tr.querySelector('td:nth-child(4) td');if(sel&&sel.options.length>1&&qtyTd){batchTracker.set(sel,qtyTd)}});observeBatchTable()}
function observeBatchTable(){const table=document.getElementById('pt1:r1:0:pt1:t1::db');if(!table)return;const observer=new MutationObserver(mutations=>{for(const mutation of mutations){for(const node of mutation.addedNodes){if(node.nodeType!==1||node.tagName!=='TR')continue;const select=node.querySelector('select');if(select&&select.options.length>1){setTimeout(()=>{applyBatchColorLogic(select)},50)}}}});observer.observe(table,{childList:!0})}
function computeKey(selectElem){const tr=selectElem.closest('tr[_afrrk]');let rowKey=tr?tr.getAttribute('_afrrk'):null;const td=selectElem.closest('td[id]');let colKey=null;if(td){const m=td.id.match(/:c(\d+)$/);if(m)colKey=m[1]}
if(rowKey!=null&&colKey!=null)return rowKey+':'+colKey;if(selectElem.id)return'id:'+selectElem.id;if(selectElem.name)return'name:'+selectElem.name;return null}
function chooseBestBatch(selectElem){     if(selectElem.options.length<=1)return;const opts=Array.from(selectElem.options);const piecesList=opts.map(opt=>{const tokens=opt.textContent.trim().split(/\s+/);const pieceToken=tokens.find(t=>/^\d{1,3}$/.test(t));return pieceToken?parseInt(pieceToken,10):0});const unique=Array.from(new Set(piecesList));if(unique.length===1){const allCount=unique[0];return}
const maxCount=Math.max(...piecesList);const chosenIdx=piecesList.indexOf(maxCount);const opt=selectElem.options[chosenIdx];selectElem.focus();selectElem.selectedIndex=chosenIdx;selectElem.value=opt.value;selectElem.dispatchEvent(new Event('input',{bubbles:!0}));selectElem.dispatchEvent(new Event('change',{bubbles:!0}));setTimeout(()=>selectElem.blur(),0);applyBatchColorLogic(selectElem);const tr=selectElem.closest('tr');if(tr){const cells=tr.querySelectorAll('td');if(cells.length>3){const valCell=cells[3].querySelector('table td');const expected=valCell&&parseInt(valCell.textContent.trim(),10);if(expected!==maxCount){selectElem.style.backgroundColor='#ffadad'}}}}
function handleSelect(selectElem){const container=document.getElementById(PANELBOX_ID);if(!container||!container.contains(selectElem))return;const key=computeKey(selectElem);if(key&&window._processedSelectKeys.has(key))return;chooseBestBatch(selectElem);if(key)window._processedSelectKeys.add(key);focusSearchInput()}
function onUserKeydown(e){if([' ','Enter'].includes(e.key)||e.code==='NumpadEnter'){const active=document.activeElement;if(active&&(active.tagName==='INPUT'||active.tagName==='TEXTAREA'||active.isContentEditable)){return}
e.preventDefault();document.getElementById("pt1:r1:0:pt1:createBtn").click()
focusSearchInput()}}
function focusSearchInput(){const input=document.getElementById(SEARCH_INPUT_ID);if(input){try{input.focus()}catch(err){}}}
function applyBatchColorLogic(selectElem){if(selectElem.options.length<=1)return;const options=Array.from(selectElem.options);const piecesList=options.map(opt=>{const tokens=opt.textContent.trim().split(/\s+/);const nums=tokens.filter(t=>/^\d{1,3}$/.test(t)).map(Number);return nums.length?Math.min(...nums):null});const unique=[...new Set(piecesList.filter(Boolean))];if(unique.length===1){const val=unique[0];if(val===1){selectElem.style.backgroundColor='#ff0000'}else{selectElem.style.backgroundColor='#ffe9c1'}
return}
const maxCount=Math.max(...piecesList);const chosenIdx=piecesList.indexOf(maxCount);   /*  const opt=selectElem.options[chosenIdx];selectElem.selectedIndex=chosenIdx;selectElem.value=opt.value;selectElem.focus();selectElem.dispatchEvent(new Event('input',{bubbles:!0}));selectElem.dispatchEvent(new Event('change',{bubbles:!0}));setTimeout(()=>selectElem.blur(),0);    */    const tr=selectElem.closest('tr');const quantityTd=tr?.querySelector('td:nth-child(4) td');const actualQty=quantityTd?parseInt(quantityTd.textContent.trim()):null;if(actualQty!=null){if(actualQty===maxCount&&selectElem.options.length>1){selectElem.style.backgroundColor='#ffc04d'}else if(actualQty!==maxCount){selectElem.style.backgroundColor='#ffadad'}}
focusSearchInput()}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init)}else{init()};document.addEventListener('keydown',function(e){if(e.key==='Escape'){const panel=document.getElementById('pt1:r1:0:pt1:pw4');if(panel&&panel.offsetParent!==null){const btn=document.getElementById('pt1:r1:0:pt1:b25');if(btn)btn.click();}}});let lastKeyTime=0;document.addEventListener("keydown",function(e){const now=Date.now();if(now-lastKeyTime<30)return;lastKeyTime=now;if(!e.isTrusted)return;if(!document.getElementById('pt1:r1:0:pt1:PopPay::content'))return;if(e.which===226){if(document.querySelector('._quickPopupOverlay'))return;e.preventDefault();const cashInput=document.getElementById('pt1:r1:0:pt1:itCashAmmount::content');const amtInput=document.getElementById('pt1:r1:0:pt1:itAtmAmmount::content');const source=document.getElementById('pt1:r1:0:pt1:ot34');const btn=document.getElementById('pt1:r1:0:pt1:b37');function ok(){if(confirm('Do you want to save '+source.innerHTML+" as ATM ?")){btn.click()}else{}}
if(amtInput&&source&&btn){amtInput.setAttribute('value',source.innerHTML);cashInput.setAttribute('value','0');const amount=parseFloat(source.innerHTML.replace(/[^\d.]/g,''))||0;sendToGeidea(amount);ok()}}});document.addEventListener("keydown",function(e){if(!document.getElementById('pt1:r1:0:pt1:PopPay::content'))return;if(e.code==="NumpadSubtract"){if(document.querySelector('._quickPopupOverlay'))return;e.preventDefault();const cashInput=document.getElementById('pt1:r1:0:pt1:itCashAmmount::content');const amtInput=document.getElementById('pt1:r1:0:pt1:itAtmAmmount::content');const source=document.getElementById('pt1:r1:0:pt1:ot34');const btn=document.getElementById('pt1:r1:0:pt1:b37');function ok(){if(confirm('Do you want to save '+source.innerHTML+" as Cash ?")==!0){btn.click()}};if(cashInput&&source&&btn){cashInput.setAttribute('value',source.innerHTML);amtInput.setAttribute('value','0');ok()}}});document.addEventListener('keydown',function(e){if(e.which===112){e.preventDefault();const tableBody=document.querySelector('#pt1\\:r1\\:0\\:pt1\\:t1\\:\\:db tbody');if(!tableBody)return;const rows=tableBody.querySelectorAll('tr');if(rows.length===0)return;const lastRow=rows[0];const codeSpan=lastRow.querySelector('td:nth-child(2) span[id$="itemCodeId\\:\\:content"]');if(!codeSpan)return;const itemCode=codeSpan.textContent.trim();if(!itemCode)return;const input=document.getElementById('pt1:r1:0:pt1:it22::content');if(!input)return;input.value=itemCode;input.focus();input.dispatchEvent(new Event('input',{bubbles:!0}));document.getElementById('pt1:r1:0:pt1:b33')?.click()}});document.addEventListener('keydown',function(e){if(e.which===192){e.preventDefault();const tableBody=document.querySelector('#pt1\\:r1\\:0\\:pt1\\:t1\\:\\:db tbody');if(!tableBody)return;const firstRow=tableBody.querySelector('tr');if(!firstRow)return;const deleteButtonDiv=firstRow.querySelector('div[id$=":b14"]');deleteButtonDiv.click();focusSearchInput()}})})();(function(){let lastKeyTime=0;function sendToGeidea(amount){fetch('http://localhost:5000/charge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount})})}
document.addEventListener("keydown",function(e){const now=Date.now();if(now-lastKeyTime<30)return;lastKeyTime=now;if(!e.isTrusted)return;if(e.which===81){if (document.activeElement && document.activeElement.id === 'pt1:r1:0:pt1:it222::content') { return;};e.preventDefault();const overlay=document.querySelector('._quickPopupOverlay');if(overlay){okQuickPopup()}else{showQuickPopup()}}});function showQuickPopup(){removeExistingPopup();const sourceElem=document.getElementById('pt1:r1:0:pt1:ot34');if(!sourceElem)return;const raw=sourceElem.innerText.trim();const sourceValue=parseFloat(raw);if(isNaN(sourceValue))return;const overlay=document.createElement('div');overlay.classList.add('_quickPopupOverlay');Object.assign(overlay.style,{position:'fixed',top:'0',left:'0',width:'100vw',height:'100vh',backgroundColor:'rgba(0,0,0,0.5)',zIndex:'100000',display:'flex',alignItems:'center',justifyContent:'center'});const modal=document.createElement('div');modal.classList.add('_quickPopupModal');Object.assign(modal.style,{backgroundColor:'#fff',borderRadius:'6px',padding:'16px',boxShadow:'0 2px 10px rgba(0,0,0,0.3)',maxWidth:'90%',width:'300px',boxSizing:'border-box'});function makeField(labelText,inputId){const wrapper=document.createElement('div');wrapper.style.marginBottom='10px';const label=document.createElement('label');label.textContent=labelText;label.setAttribute('for',inputId);label.style.display='block';label.style.fontSize='0.9em';label.style.marginBottom='4px';const input=document.createElement('input');input.type='number';input.id=inputId;input.style.width='100%';input.style.padding='6px';input.style.boxSizing='border-box';input.style.fontSize='1em';wrapper.appendChild(label);wrapper.appendChild(input);return{wrapper,input}}
const{wrapper:changeWrapper,input:changeGivenInput}=makeField('Cash Given','_quickPopup_cashGiven');const sourceWrapper=document.createElement('div');sourceWrapper.style.marginBottom='10px';const sourceLabel=document.createElement('div');sourceLabel.textContent='Source Value:';sourceLabel.style.fontSize='0.9em';sourceLabel.style.marginBottom='4px';const sourceDisplay=document.createElement('div');sourceDisplay.textContent=raw;Object.assign(sourceDisplay.style,{padding:'6px',border:'1px solid #ccc',borderRadius:'4px',background:'#f5f5f5',fontSize:'1em',textAlign:'right'});sourceWrapper.appendChild(sourceLabel);sourceWrapper.appendChild(sourceDisplay);const{wrapper:cashWrapper,input:cashInput}=makeField('Cash','_quickPopup_cash');const{wrapper:atmWrapper,input:atmInput}=makeField('ATM','_quickPopup_atm');const changeResultWrapper=document.createElement('div');changeResultWrapper.style.marginBottom='10px';const changeResultLabel=document.createElement('div');changeResultLabel.textContent='Change:';changeResultLabel.style.fontSize='0.9em';changeResultLabel.style.marginBottom='4px';const changeResultDisplay=document.createElement('div');changeResultDisplay.textContent='';Object.assign(changeResultDisplay.style,{padding:'6px',border:'1px solid #ccc',borderRadius:'4px',background:'#f5f5f5',fontSize:'1em',textAlign:'right'});changeResultWrapper.appendChild(changeResultLabel);changeResultWrapper.appendChild(changeResultDisplay);const closeBtn=document.createElement('button');closeBtn.type='button';closeBtn.textContent='Close';Object.assign(closeBtn.style,{marginTop:'8px',padding:'6px 12px',borderRadius:'4px',border:'1px solid #ccc',background:'#fafafa',cursor:'pointer'});closeBtn.addEventListener('click',removeExistingPopup);modal.appendChild(changeWrapper);modal.appendChild(sourceWrapper);modal.appendChild(cashWrapper);modal.appendChild(atmWrapper);modal.appendChild(changeResultWrapper);modal.appendChild(closeBtn);overlay.appendChild(modal);document.body.appendChild(overlay);window._quickPopupFields={sourceValue,cashInput,atmInput,changeGivenInput,changeResultDisplay};changeGivenInput.focus();changeGivenInput.select();function recalcChange(){const given=parseFloat(changeGivenInput.value);const cashVal=parseFloat(cashInput.value);if(isNaN(given)||isNaN(cashVal)){changeResultDisplay.textContent='';return}
const ch=given-cashVal;changeResultDisplay.textContent=ch.toFixed(2)};cashInput.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();const cashVal=parseFloat(cashInput.value);if(isNaN(cashVal))return;if(cashVal!==sourceValue){const leftover=sourceValue-cashVal;atmInput.value=leftover.toFixed(2);applyToUnderlying();atmInput.focus();atmInput.select()}else{atmInput.value='0';applyToUnderlying()}
recalcChange()}});atmInput.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();const atmVal=parseFloat(atmInput.value);if(isNaN(atmVal))return;if(atmVal!==sourceValue){const leftover=sourceValue-atmVal;cashInput.value=leftover.toFixed(2);applyToUnderlying();cashInput.focus();cashInput.select()}else{cashInput.value='0';applyToUnderlying()}
recalcChange()}});changeGivenInput.addEventListener('input',recalcChange);changeGivenInput.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();const given=parseFloat(changeGivenInput.value);const cashElem=document.getElementById('pt1:r1:0:pt1:itCashAmmount::content');if(cashElem){if(!isNaN(given)){cashElem.setAttribute('value',given.toFixed(2))}else{cashElem.setAttribute('value',sourceValue.toFixed(2))}}
cashInput.value=sourceValue;cashInput.focus();cashInput.select();recalcChange()}});cashInput.addEventListener('input',recalcChange);atmInput.addEventListener('input',recalcChange);function applyToUnderlying(){const cashElem=document.getElementById('pt1:r1:0:pt1:itCashAmmount::content');const atmElem=document.getElementById('pt1:r1:0:pt1:itAtmAmmount::content');if(cashElem){const cashGivenVal=changeGivenInput.value.trim();if(cashGivenVal!==''){cashElem.setAttribute('value',parseFloat(cashGivenVal).toFixed(2))}else{cashElem.setAttribute('value',cashInput.value)}}
if(atmElem){atmElem.setAttribute('value',atmInput.value)}}
function onEsc(e){if(e.key==='Escape'){removeExistingPopup()}}
document.addEventListener('keydown',onEsc);function focusSearchInput(){const input=document.getElementById('pt1:r1:0:pt1:it22::content');if(input){try{input.focus()}catch(err){}}};function removeExistingPopup(){const oldOverlay=document.querySelector('._quickPopupOverlay');if(oldOverlay)oldOverlay.remove();document.removeEventListener('keydown',onEsc);delete window._quickPopupFields;focusSearchInput()}}
function okQuickPopup(){const fields=window._quickPopupFields;if(!fields)return;const{sourceValue,cashInput,atmInput}=fields;let cashVal=parseFloat(cashInput.value);let atmVal=parseFloat(atmInput.value);if(isNaN(cashVal))cashVal=0;if(isNaN(atmVal))atmVal=0;function roundUp2(n){return Math.ceil(n*100)/100}
const cashRounded=roundUp2(cashVal).toFixed(2);const atmRounded=roundUp2(atmVal).toFixed(2);const msg=`Do you want to save Cash: ${cashRounded} and ATM: ${atmRounded}?`;const amount=parseFloat(atmRounded.replace(/[^\d.]/g,''))||0;sendToGeidea(amount);if(confirm(msg)){const cashElem=document.getElementById('pt1:r1:0:pt1:itCashAmmount::content');const atmElem=document.getElementById('pt1:r1:0:pt1:itAtmAmmount::content');if(cashElem){}
if(atmElem){atmElem.setAttribute('value',atmRounded)}
const btn=document.getElementById('pt1:r1:0:pt1:b37');if(btn)btn.click();const oldOverlay=document.querySelector('._quickPopupOverlay');if(oldOverlay)oldOverlay.remove();delete window._quickPopupFields}}
document.addEventListener("keydown",function(e){const overlay=document.querySelector("._quickPopupOverlay");if(!overlay)return;if(e.which===226||e.which===109){e.preventDefault();okQuickPopup()}})})();(function(){const IFRAME_ID='pt1:r1:0:pt1:if2';const observer=new MutationObserver(muts=>{for(const m of muts){for(const n of m.addedNodes){if(n.tagName==='IFRAME'&&n.id===IFRAME_ID){n.addEventListener('load',()=>n.contentWindow.print())}}}});observer.observe(document.body,{childList:!0,subtree:!0});document.addEventListener("keydown",function(e){if (e.which===46) {document.activeElement.parentElement.getElementsByTagName("table")[0].getElementsByTagName("td")[4].getElementsByTagName("span")[1].firstChild.click()}})})()

